# Generated by Django 2.2.7 on 2019-11-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField(verbose_name='Latitude')),
                ('Long', models.FloatField(verbose_name='Longitude')),
                ('Uni', models.CharField(max_length=100, verbose_name='Unique Squirrel ID')),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, verbose_name='Shift')),
                ('Date', models.DateField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
