# Generated by Django 2.2.7 on 2019-11-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Squirrel',
        ),
    ]
