# Generated by Django 2.2.7 on 2019-11-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20191121_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Primary_fur_color',
            field=models.CharField(default='black', max_length=100, verbose_name='Primary Fur Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(max_length=100, verbose_name='Age'),
        ),
    ]
