# Generated by Django 2.2.7 on 2019-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0005_auto_20191128_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(default='', max_length=100, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Other_activities',
            field=models.CharField(default='', max_length=100, verbose_name='Other Activities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Runs_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Specific_location',
            field=models.CharField(default='', max_length=100, verbose_name='Specific Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.BooleanField(default=False),
        ),
    ]
