# Generated by Django 2.2.7 on 2019-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20191128_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Lat',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
    ]
